#!/bin/bash
if ! [ $(id -u) = 0 ]; then
      echo "I am not root!"
      exit 1
fi

FILEPATH="/etc/hosts"
cat $FILEPATH | while read -r line ; do
      if echo $line | grep -q youtu
      then
            OUT=#
            OUT+=$line
            sed -i.bak "s/$line/$OUT/" $FILEPATH

            echo $line
            echo $OUT
      fi
done
